version: '4'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysql'
    ports:
      - '3306'
    volumes:
      - './mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './docker/mysql/data:/var/lib/mysql'
